# -*- coding: utf-8 -*-
"""factorial

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_AiSn2V0mHh_VyjV9Ysw7BhIei3oRZNE
"""

def factorial(n):
    if n < 0:
        return "Factorial is not defined for negative numbers."
    result = 1
    for i in range(1, n + 1):
        result *= i
    return result

n = int(input("Enter a number: "))
print("Factorial:", factorial(n))